export const data = {
    en:{
        title : "riverdelta",
        setLang : "Setting Langauge",
        mainTitle : "A good meal makes a good trip",
        subTitle : "There is a Korean saying: Food before Mt. Geumgang. It means a good view can only be enjoyed when you are full. We guide the route between travel destinations and halal restaurants so that everyone who visits Korea can enjoy a comfortable meal. We hope to make your trip more colorful, River Delta",
        setApp : "Install Application",
        findPlace : "FindPlace",
        rest : "Restaurant",
        att : "Attraction",
        mos : "Mosque",
        howTo : "How To Use Application Version",
        setLoc : "LocationSetting",
        choCity : "Choose a City",
        choMet : "Metropolitan",
        Seoul : "Seoul",
        Incheon : "Incheon",
        Daejeon : "Daejeon",
        Daegu : "Daegu",
        Gwangju : "Gwangju",
        Busan : "Busan",
        Jeju : "Jeju",
        subCity : "City/Country",
        restTitle :"Restaurant",
        noRes : "No Result",
        filter : "Filter",
        foodType : "Food Type",
        buffet : "Buffet",
        asia : "Asian",
        western : "Western",
        india : "Indian",
        japan : "Japanese",
        china : "Chinese",
        turkey : "Turkish",
        kor : "Korean Cuisine",
        etc : "Etc",
        standard : "Halal Standard",
        certified : "Halal Certified",
        MusFriendly : "Muslim Friendly",
        porkFree : "Pork Free",
        selfCerti : "Self Certified",
        cancel : "Cancel",
        apply : "Apply",
        phone : "Phonenum",
        holiday : "Holiday",
        runtime : "Runtime",
        addr : "Address",
        standard : "Halal Friendly",
        parking : "Parking",
        way : "Way to Come",
        zoom : "Zoom in or zoom out on the map.",
        zoomLoc : "The location of nearby tourist attractions is indicated by a yellow star.",
        nearAttr : "Nearby Attractions",
        attrTitle : "Attraction",
        attraction : "Attraction",
        cultFaci :  "Cultural facility",
        fest : "Festival",
        sports : "Sports",
        lodg : "Lodgment",
        shopping : "Shopping",
        nearbyRest : "Nearby Restaurant",
        mosqTitle : "Mosque",
        mosq : "Mosque",
        prayerroom :  "Prayer room",
        worship : "Place of Worship",
        prayer : "Place of Prayer",
        nation : "nation",
        type : "type",
        suggRest : "Recommended restaurant",
        suggAttr : "Recommended sightseeing spots"
    },
    kr:{
        title : "리버델타",
        setLang : "언어설정",
        mainTitle : "좋은 식사가 좋은 여행을 만듭니다",
        subTitle : "다음과 같은 한국 속담이 있습니다: 금강산도 식후경이다. 좋은 경치도 배가 불러야 눈에 들어온다는 뜻입니다. 우리는 한국을 방문하는 모두가 편안한 한 끼를 먹을 수 있도록, 여행지와 할랄 식당 사이의 동선을 안내합니다. 당신의 여행이 더욱 다채롭기를 바라며, 리버델타.",
        setApp : "어플리케이션 설치",
        findPlace : "장소 찾기",
        rest : "식당",
        att : "관광지",
        mos : "모스크",
        howTo : "APP 버전 사용 방법",
        setLoc : "위치설정",
        choCity : "도시를 선택하세요",
        choMet : "광역시",
        Seoul : "서울",
        Incheon : "인천",
        Daejeon : "대전",
        Daegu : "대구",
        Gwangju : "광주",
        Busan : "부산",
        Jeju : "제주",
        subCity : "시/군/구",
        restTitle :"식당",
        noRes : "검색 결과가 존재하지 않습니다",
        filter : "필터",
        foodType : "음식 종류",
        buffet : "뷔페",
        asia : "아시아",
        western : "양식",
        india : "인도",
        japan : "일본",
        china : "중국",
        turkey : "터키",
        kor : "한식",
        etc : "그 외",
        standard : "할랄 유형",
        certified : "할랄 공식 인증",
        MusFriendly : "무슬림 프렌들리",
        porkFree : "포크 프리",
        selfCerti : "무슬림 자가 인증",
        cancel : "취소",
        apply : "적용",
        phone : "전화번호",
        holiday : "휴무일",
        runtime : "운영시간",
        addr : "주소",
        standard : "할랄유형",
        parking : "주차",
        way : "오시는 길",
        zoom : "지도를 확대하거나 축소해보세요.",
        zoomLoc : "주변 관광지의 위치가 노란 별로 표시됩니다.",
        nearAttr : "주변 관광지",
        attrTitle : "관광지",
        attraction : "관광지",
        cultFaci :  "문화시설",
        fest : "행사/공연/축제",
        sports : "레포츠",
        lodg : "숙박",
        shopping : "쇼핑",
        nearbyRest : "주변 식당",
        mosqTitle : "모스크",
        mosq : "성원",
        prayerroom :  "기도실",
        worship : "예배소",
        prayer : "기도처",
        nation : "국적",
        type : "유형",
        suggRest : "추천 식당",
        suggAttr : "추천 관광지"
    }
}